### ISSUE TITLE
创建伸缩配置

### ISSUE THREAD

**Issue by lishaohui2019** [huaweicloudDocs/as#1]
建议将“使用已有云服务器创建伸缩配置”、“使用新模板创建伸缩配置”两个页面合并至页面“创建伸缩配置”中，以section的形式体现创建伸缩配置的两种方式。

**Comment by chengnan6** [comment]
> 建议将“使用已有云服务器创建伸缩配置”、“使用新模板创建伸缩配置”两个页面合并至页面“创建伸缩配置”中，以section的形式体现创建伸缩配置的两种方式。

在“创建伸缩配置”页面给出了场景的介绍，并给出了到对应页面的链接
